name: First_YAML_Tests

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Setting Python Up
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Dependency Installation
        run: pip install -r requirements.txt
        working-directory: ./Tests

      - run:
          python WordHidder_test.py
        working-directory: ./Tests
        